[programs.devnet]
myepicproject = "HkFfzg6Mpq6PwDc9ACwNrsPaA1XRFXcE2yLEoWb4qPDr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/horaciolopez2020/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
